### ISSUE TITLE
Trying, but no haml updates are processed. And a error.

### ISSUE THREAD

**Issue by hlogmans** [Zozos/ionic-with-haml-sass-coffee#1]
Hi, I was wondering how to activate the automate the process of converting Haml (I love HAML).

Wen doing ionic serve, I get the error 
Error: Cannot find module 'gulp-dest'

Installed it with npm install gulp-dest --save-dev

Then no error, but still no compilation of HAML...

Does this still work for you?

**Comment by hlogmans** [comment]
It seems the gulp-dest module is causing this behaviour. Reworking code by removing this module and putting the arguments directly in gulp.dest(...) solves the problem. (Only tested for HAML)

**Comment by salarali** [comment]
I pushed a new version that uses gulp-cached. Try now.

**Comment by hlogmans** [comment]
Confirmed, it works now. Thanks!
